### ISSUE TITLE
Pn-tools

### ISSUE THREAD

**Issue by Ivan0x17** [st-one-io/node-red-contrib-s7#104]
What is pn-tools?

Directory

/src/tools.js

Line 12 = const pnToolsPath='pn-tools';

**Comment by Sulomus** [comment]
+1 I would love to know too!

I am in need to use PROFINET with diffrent kind of PLC then Siemens, and I would like to use the "core" of this project as a starting building block for it.

Does anyone have any idea what is "pn-tools"? @Ivan0x17 have you figured it out?

**Comment by Ivan0x17** [comment]
> +1 I would love to know too!
> 
> 
> 
> I am in need to use PROFINET with diffrent kind of PLC then Siemens, and I would like to use the "core" of this project as a starting building block for it.
> 
> 
> 
> Does anyone have any idea what is "pn-tools"? @Ivan0x17 have you figured it out?

Unfortunately I don't know what it is pn-tools

**Comment by fernandoamorim1703** [comment]
pn-tools is our internal tool to check how many and which PLCs are connected to the network

**Comment by fernandoamorim1703** [comment]
We will be closing this issue, if there is a need to revisit the subject, please open a new one. Thank you very much.
