### ISSUE TITLE
an integration with mqtt to Homeassistant would be cool :)

### ISSUE THREAD

**Issue by BOB9691** [st-one-io/node-red-contrib-s7#107]
an integration with mqtt to Homeassistant would be cool.
i love your integration . keep it up

https://www.home-assistant.io/

**Comment by fernandoamorim1703** [comment]
Unfortunately it is not part of our scope. Our focus is the digitization of the industry, communicating with PLC to read/write information

**Comment by fernandoamorim1703** [comment]
We will be closing this issue, if there is a need to revisit the subject, please open a new one. Thank you very much.
