### ISSUE TITLE
Support s7-200 smart plc?

### ISSUE THREAD

**Issue by toplinuxsir** [st-one-io/node-red-contrib-s7#113]
Support s7-200 smart plc?

**Comment by fernandoamorim1703** [comment]
Hello @toplinuxsir ,

Analyzing the manual of the S7-200 Smart, I saw that it is possible to connect an RJ45 cable, so it might work through this port. I would have to test it to be sure.

Unfortunately, it doesn't work via the serial port

We will be closing this issue, if there is a need to revisit the subject, please open a new one. Thank you very much.
