### ISSUE TITLE
In and out nodes are in-resposive after timeout on http-request

### ISSUE THREAD

**Issue by KblAtBila** [st-one-io/node-red-contrib-s7#118]
### Describe the bug
When i have a timeout on a http-request node the whole node-red server are “freezing”. After a fem min. the server returns to normal state but offen the in and out s7 are down and i have to restart the server

I have contrib-s7 3.0.0 and node-red 2.1.4 on a Windows 10

Have any of you seen this before?

Any help a greatly valued!

BR Kristian

**Comment by EricWeinz** [comment]
Did you find any answers for your problem?

**Comment by KblAtBila** [comment]
> Did you find any answers for your problem?

The problem was a never ending loop that caused the system to freeze. After fixing the loop the issue have been gone!
