### ISSUE TITLE
Invalid properties S7 endpoint with nodered V3.0.2 Node.js 18.14.0 -Windows 10

### ISSUE THREAD

**Issue by Paolind** [st-one-io/node-red-contrib-s7#120]
Hi, the system gives me an error when I try to configure manually S7 endpoint to comand a light and a motorized roller shutter with nodered V3.0.2 Node.js 18.14.0 running with Windows 10. The strange thing is that when I import the same (two) flows from another Nodered instance (v.0.19.5) this problem doesn't appear for the light while persist for the motorized roller shutter. I double checked the differences between the two vesione of S7 endpoint but they seems to me filled with the same data and this  is corroborated from the fact that ONLY Once, when i use the imported flow for the motorized roller shutter in the windows machine, the shutter works, but then, when I try to move again the shutter, the system doesn't react. It is like the PLC accept only once the input and then fail. I am able to restart the system with the same flow using S7 with nodered instance v.0.19.5. Has anyone an Idea of the reason why the system react in this way? Thanks a million in advance, best regards. Paolo

**Comment by tiscali19** [comment]
Hi, I have the same problem! Have a solution?

**Comment by Paolind** [comment]
I’m out of home, furthermore after i fixed my problems I didn’t enter the system again, i don’t know if it helps you… try with the blue one.
regards
Paolo



Inviato da iPhone

**Comment by tiscali19** [comment]
Paolo, are you italian?

**Comment by Paolind** [comment]
si

**Comment by tiscali19** [comment]
> si

Scusami, mi puoi dire più o meno cosa hai fatto? Sono bloccato...

**Comment by Paolind** [comment]
Ciao, hai visto lo screenshot che ti ho mandato? ho installato il pacchetto cerchiato in verde dopo aver disinstallato il rosso

Inviato da iPhone

**Comment by Paolind** [comment]
Blue non verde😅
Inviato da iPhone

**Comment by tiscali19** [comment]
Non vedo nessuna immagine...

**Comment by Paolind** [comment]
io ho installato il pacchetto il blue (dopo aver disinstallato quello in rosso)
giusto per curiosità fammi sapere se hai risolto


Inviato da iPhone

**Comment by tiscali19** [comment]
Anche adesso non c'è nessuna immagine allegata. Mi puoi scrivere i nomi dei pacchetti?

**Comment by Paolind** [comment]
mandami n cell ti mando wtsp

Inviato da iPhone

**Comment by tiscali19** [comment]
+39 320 8576621

**Comment by Paolind** [comment]
non ti trovo su wtspp

io avevo installato

plcindustry   (versione 2.1.1) 

e disinstallato 

node-red-contib-s7

Inviato da iPhone

**Comment by tiscali19** [comment]
Ok, grazie, lo provo. Per Whatsapp hai scritto il numero giusto?
