### ISSUE TITLE
Necessary Steps for using MPI-USB Adapter

### ISSUE THREAD

**Issue by sniicker** [st-one-io/node-red-contrib-s7#73]
Readme says :  "An optional compilation step is only necessary for supporting MPI-USB adapter."

What steps? Where can i find this informations?

**Comment by gfcittolin** [comment]
Sorry, support for MPI is very experimental at this stage, and we have no clear instructions at the moment. I'll add this note on the readme on the next release, and a link pointing out to the installation instructions on the mpi-s7 repo

**Comment by gfcittolin** [comment]
I'm closing this for now, as the whole MPI functionality is moving out of this node into a separate one.
