### ISSUE TITLE
Array of Structure Read

### ISSUE THREAD

**Issue by INDRANI125** [st-one-io/node-red-contrib-s7#92]
How I can read elements in array of structures/array/PLC data type using this? I do not see anything in documentation

**Comment by fernandoamorim1703** [comment]
If I understand your question correctly, you need to do the following.

You need to declare as follows:
DB1,DW0.6

The last numeric value (.6) refers to the number of elements you would like to read, thus returning an array of data.

**Comment by fernandoamorim1703** [comment]
We will be closing this issue, if there is a need to revisit the subject, please open a new one. Thank you very much.
