### ISSUE TITLE
Error connecting to PLC: Error: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by digidax** [st-one-io/node-red-contrib-s7#95]
Coming from 
[https://github.com/st-one-io/node-red-contrib-s7/issues/26](https://github.com/st-one-io/node-red-contrib-s7/issues/26)

Is there a way to suppress the warning in debug log without moving it to disabled flow?
I have S7-CPU of machines which are not working 24/7, so if they are switched off, I get the warning.
Programming in Node Red and watching the debug log for important debug node entries are filling over it with this warning.

**Comment by fernandoamorim1703** [comment]
We will be closing this issue, if there is a need to revisit the subject, please open a new one. Thank you very much.
